server:
  port: 8080
spring:
  application:
    name: "NisumJava"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:nisumdb"
    username: "sa"
    password: ""
    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
schema:
  email-pattern: "^[A-Za-z0-9._+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$"
  password-pattern: "^(?=.*[A-Z])(?=.*[0-9])[A-Za-z\\d]{8,}$"
#logging:
#  level:
#    org.hibernate: INFO

