server:
  port: 8080
spring:
  application:
    name: "NisumJava"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:nisumdb"
    #url: "jdbc:h2:file:./data/demo_db"
    username: "sa"
    password: ""
    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    #com.zaxxer.hikari: DEBUG
    org.hibernate: INFO

